// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TweetFormController from "./tweet_form_controller"
application.register("tweet_form", TweetFormController)
