version: "3.8"

services:
  # db:
    # container_name: postgres_database
    # image: postgres
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: twitter_clone_development
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - postgres:/var/lib/postgresql/data
    # networks:
    #   - twitter-clone
  
  db:
    image: mysql:5.7
    volumes:
      - twitter_clone_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: twitter_clone_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
    - twitter-clone

  web:
    container_name: twitter-clone-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/service.pid && cd /projects/twitter-clone && printenv && rails s -p 4500 -b '0.0.0.0'"
    volumes:
      - /Users/masroor/docker-data/ruby3.1.1/twitter-clone:/projects/twitter-clone
    ports:
      - "4500:4500"
    depends_on:
      - db
      # - redis
    env_file:
      - .env
    # App's .env file variables have precendence over the dockerfile env variables
    environment:
      # - DATABASE_HOST=db
      # - DATABASE_NAME=twitter_clone_development
      # - DATABASE_USERNAME=postgres
      # - DATABASE_PASSWORD=postgres
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_PORT=3307
      - MYSQL_DB=twitter_clone_development
      # - REDIS_URL=redis://redis:6379/1
    networks:
      - twitter-clone

  # redis:
  #   container_name: redis
  #   image: "redis:6.0"
  #   command: "redis-server"
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis:/data
  #   networks:
  #     - twitter-clone

  # sidekiq:
  #   container_name: sidekiq
  #   depends_on:
  #     - db
  #     - redis
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   command: sidekiq -C config/sidekiq.yml
  #   # command: bundle exec sidekiq -C config/sidekiq.yml
  #   volumes:
  #     - .:/project
  #   # App's .env file variables have precendence over the dockerfile env variables
  #   environment:
  #     - REDIS_URL=redis://redis:6379/1
  #     - DATABASE_HOST=db
  #     - DATABASE_USERNAME=postgres
  #     - DATABASE_PASSWORD=postgres
  #   networks:
  #     - twitter-clone

volumes:
  # twitter-clone:
  #   name: "twitter-clone"
  # postgres:
  twitter_clone_mysql:
  # redis:

networks:
  twitter-clone:
    name: "twitter-clone"